buildTests:
   stage: build
   script:
      - make testGame
      - make game
   artifacts:
      paths:
         - testGame

test:
   stage: test
   script:
      - testGame
      - make coverage
      - make memcheck-test
   artifacts:
      paths:
         - coverage
         - memcheck.xml
      expire_in: 14 days

docs:
   stage: deploy
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 14 days

