buildTests:
   stage: build
   script:
      - make testShapes
   artifacts:
      paths:
         - testShapes

test:
   stage: test
   script:
      - testShapes
      - make coverage
      - make memcheck-test
   artifacts:
      paths:
         - coverage
         - memcheck.xml
      expire_in: 14 days

docs:
   stage: deploy
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 14 days

